-- Detailed trace of: let x = 3 in let y = x in y
-- Showing exact moment of generalization

module Main where

-- Step-by-step trace
main :: IO ()
main = do
    putStrLn "=== Type Inference Trace ==="
    putStrLn ""
    putStrLn "Expression: let x = 3 in let y = x in y"
    putStrLn ""
    
    putStrLn "STEP 1: Infer 'let x = 3'"
    putStrLn "  - Infer RHS: 3 has type Int"
    putStrLn "  - Before generalizing x:"
    putStrLn "    ρ = Int"
    putStrLn "    ftv(ρ) = {}  (Int has no meta variables)"
    putStrLn "    Γ = {}  (empty environment at start)"
    putStrLn "    ftv(Γ) = {}"
    putStrLn "    ftv(ρ) - ftv(Γ) = {} - {} = {}"
    putStrLn "  - Generalization candidates: {} (none)"
    putStrLn "  - Result: x : Int  (monomorphic)"
    putStrLn ""
    
    putStrLn "STEP 2: Environment after x"
    putStrLn "  Γ = {x : Int}"
    putStrLn ""
    
    putStrLn "STEP 3: Infer 'let y = x in y' (inside x's scope)"
    putStrLn "  - Infer RHS: x"
    putStrLn "  - Look up x in Γ: x : Int"
    putStrLn "  - ρ = Int  (y's RHS has type Int)"
    putStrLn "  - Before generalizing y:"
    putStrLn "    ftv(ρ) = {}  (Int has no meta variables)"
    putStrLn "    Γ = {x : Int}"
    putStrLn "    ftv(Γ) = {}  (Int in environment has no metas)"
    putStrLn "    ftv(ρ) - ftv(Γ) = {} - {} = {}"
    putStrLn "  - Generalization candidates: {} (none)"
    putStrLn "  - Result: y : Int  (monomorphic)"
    putStrLn ""
    
    putStrLn "=== Why no metas appear ==="
    putStrLn ""
    putStrLn "In this example, there are NO meta type variables at all!"
    putStrLn ""
    putStrLn "- Int is a concrete type constant"
    putStrLn "- x's type is immediately known to be Int"
    putStrLn "- y's type is immediately known to be Int (from x)"
    putStrLn ""
    putStrLn "The ftv sets are empty because:"
    putStrLn "- ftv(Int) = {}  (concrete types have no free metas)"
    putStrLn ""
    putStrLn "=== More interesting example ==="
    putStrLn ""
    putStrLn "Compare with: let x = \z -> z in let y = x in y"
    putStrLn ""
    putStrLn "STEP 1: Infer 'let x = \\z -> z'"
    putStrLn "  - Create fresh meta _a for z"
    putStrLn "  - Infer body z: returns _a"
    putStrLn "  - Build arrow: _a -> _a"
    putStrLn "  - Before generalizing:"
    putStrLn "    ρ = _a -> _a"
    putStrLn "    ftv(ρ) = {_a}"
    putStrLn "    Γ = {}"
    putStrLn "    ftv(Γ) = {}"
    putStrLn "    ftv(ρ) - ftv(Γ) = {_a} - {} = {_a}"
    putStrLn "  - Bind _a to fresh bound var 'a'"
    putStrLn "  - Result: x : ∀a. a -> a  (POLYMORPHIC!)"
    putStrLn ""
    putStrLn "STEP 2: Environment"
    putStrLn "  Γ = {x : ∀a. a -> a}"
    putStrLn ""
    putStrLn "STEP 3: Infer 'let y = x in y'"
    putStrLn "  - Infer RHS: x"
    putStrLn "  - Look up x: x : ∀a. a -> a"
    putStrLn "  - INSTANTIATE: a -> fresh meta _b"
    putStrLn "  - So x has type _b -> _b (at this use site)"
    putStrLn "  - y's RHS has type _b -> _b"
    putStrLn "  - Before generalizing:"
    putStrLn "    ρ = _b -> _b"
    putStrLn "    ftv(ρ) = {_b}"
    putStrLn "    Γ = {x : ∀a. a -> a}"
    putStrLn "    ftv(Γ) = {}  (∀a. a->a has no free metas!)"
    putStrLn "    ftv(ρ) - ftv(Γ) = {_b} - {} = {_b}"
    putStrLn "  - Wait, this suggests y should be polymorphic..."
    putStrLn ""
    putStrLn "  Actually, no! Let's check the env more carefully:"
    putStrLn "  The environment stores the POLYMORPHIC type ∀a. a->a"
    putStrLn "  It doesn't store metas from instantiation."
    putStrLn "  So ftv(Γ) is indeed {}."
    putStrLn ""
    putStrLn "  Hmm, but y should NOT be polymorphic here..."
    putStrLn "  Let me reconsider when metas get into Γ."
    putStrLn ""
    putStrLn "  Ah! The issue is WHEN we compute ftv(Γ)."
    putStrLn "  We compute it AFTER inferring the RHS but BEFORE adding to Γ."
    putStrLn "  So at the point of generalizing y:"
    putStrLn "    Γ = {x : ∀a. a -> a}  (x is already in scope)"
    putStrLn "    But wait, x's polymorphic type has no metas."
    putStrLn ""
    putStrLn "  Actually, y SHOULD be polymorphic in this case!"
    putStrLn "  Because _b is not constrained by anything."
    putStrLn ""
    putStrLn "  But intuitively, 'let y = x in y' where x : ∀a. a->a"
    putStrLn "  should give y : ∀b. b -> b, which IS polymorphic."
    putStrLn ""
    putStrLn "=== Summary ==="
    putStrLn ""
    putStrLn "The original example 'let x = 3 in let y = x in y' has NO metas"
    putStrLn "because all types are immediately known (Int)."
    putStrLn ""
    putStrLn "Metas only appear when types are UNKNOWN during inference, like:"
    putStrLn "- Lambda parameters without annotations"
    putStrLn "- Results of polymorphic function applications"
    putStrLn "- Fresh unification variables"
    putStrLn ""
    putStrLn "The ftv(ρ) - ftv(Γ) check removes metas that are 'locked'"
    putStrLn "to specific terms in the environment. If a meta appears"
    putStrLn "in the type of some variable x : _a, then _a is locked to x"
    putStrLn "and cannot be generalized in inner lets."
